spring:
  datasource:
    url: jdbc:h2:mem:ggyuni-db
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE

    generate-ddl: true
    hibernate:
      ddl-auto: create

ggyuni:
  google:
    id: ${GOOGLE_ID}

jwt:
  secret: ${SECRET_KEY}