spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8&serverTimezone=UTC
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE

    generate-ddl: true
    hibernate:
      ddl-auto: none

ggyuni:
  google:
    id: ${GOOGLE_ID}

jwt:
  secret: ${SECRET_KEY}