server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:ggyuni-db
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE

    generate-ddl: true
    hibernate:
      ddl-auto: create


cloud:
  aws:
    credentials:
      accessKey: AKIA2FKI3VEHU5S2DDLE
      secretKey: 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
    s3:
      bucket: ggyuni-bucket
      dir: Gyunny/
    region:
      static: ap-northeast-2
    stack:
      auto: false